# Generated by Django 4.1.1 on 2022-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
