# Generated by Django 4.1.1 on 2022-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_is_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
